-- AUTO-GENERATED BY OMM VISUAL COMPILER
-- ALGO: 2 | THEME: Default

return {
  grid_cols = 12,
  grid_rows = 6,
  seed_hex = 10878975,
  components = {
    {
      id = 'err_txt', type = 'TogglePill',
      x = 120, y = 60, w = 240, h = 60, radius = 16, align = 1,
      param_key = 'unmapped', default_val = 1.000000, color_token = 'Primary', is_bipolar = false,
      label = 'SCHEMA MISSING',
      routes = {},
      get_format = function(s, v) return string.format('%.1f', v) end,
      norm_to_real = function(n) return n end,
      real_to_norm = function(r) return r end
    },
  }
}
