-- AUTO-GENERATED BY OMM VISUAL COMPILER
-- ALGO: 999 | THEME: Default
-- Protocol Zero: Macro Multiplexing Routes

return {
  grid_cols = 12,
  grid_rows = 6,
  seed_hex = 10878975,
  module_type = "BETA_LAB",
  components = {
    {
      id = '(SANDBOX)_VuMeter_3388', type = 'VuMeter',
      x = 235, y = 23, w = 219, h = 170, radius = 16, align = 1,
      param_key = 'unmapped', default_val = 0.000000, color_token = 'Teal',
      label = 'VUMETER',
      routes = {},
      get_format = function(s, v) return string.format('%.1f', v) end,
      norm_to_real = function(n) return n end,
      real_to_norm = function(r) return r end
    },
    {
      id = '(SANDBOX)_PeakMeter_1993', type = 'PeakMeter',
      x = 68, y = 23, w = 23, h = 213, radius = 16, align = 1,
      param_key = 'unmapped', default_val = 0.000000, color_token = 'Teal',
      label = 'PEAKMETER',
      routes = {},
      get_format = function(s, v) return string.format('%.1f', v) end,
      norm_to_real = function(n) return n end,
      real_to_norm = function(r) return r end
    },
  }
}
