-- AUTO-GENERATED BY OMM VISUAL COMPILER
-- ALGO: 100 | THEME: Default

return {
  grid_cols = 12,
  grid_rows = 6,
  seed_hex = 10878975,
  active_palette = {
    { id=1, hex=15073279, token='Primary', gen_index=0, hue_drift=0.000000 },
    { id=2, hex=4285216255, token='Accent', gen_index=0, hue_drift=0.000000 },
    { id=3, hex=4126537727, token='Text', gen_index=0, hue_drift=0.000000 },
    { id=4, hex=2391708671, token='Neutral', gen_index=0, hue_drift=0.000000 },
    { id=5, hex=471604991, token='Base', gen_index=0, hue_drift=0.000000 },
  },
  components = {
    {
      id = 'lfo_rate', type = 'AuraKnob',
      x = 40, y = 50, w = 60, h = 60, radius = 26, align = 1,
      param_key = 'unmapped', default_val = 1.000000, color_token = 'Primary', is_bipolar = false,
      label = 'RATE',
      routes = {},
      get_format = function(s, v) return string.format('%.1f', v) end,
      norm_to_real = function(n) return n end,
      real_to_norm = function(r) return r end
    },
    {
      id = 'lfo_depth', type = 'AuraKnob',
      x = 130, y = 50, w = 60, h = 60, radius = 26, align = 1,
      param_key = 'unmapped', default_val = 1.000000, color_token = 'Accent', is_bipolar = false,
      label = 'DEPTH',
      routes = {},
      get_format = function(s, v) return string.format('%.1f', v) end,
      norm_to_real = function(n) return n end,
      real_to_norm = function(r) return r end
    },
    {
      id = 'lfo_phase', type = 'AuraKnob',
      x = 220, y = 50, w = 60, h = 60, radius = 20, align = 1,
      param_key = 'unmapped', default_val = 0.000000, color_token = 'Neutral', is_bipolar = false,
      label = 'PHASE',
      routes = {},
      get_format = function(s, v) return string.format('%.1f', v) end,
      norm_to_real = function(n) return n end,
      real_to_norm = function(r) return r end
    },
    {
      id = 'lfo_smooth', type = 'AuraKnob',
      x = 310, y = 50, w = 60, h = 60, radius = 18, align = 1,
      param_key = 'unmapped', default_val = 0.000000, color_token = 'Neutral', is_bipolar = false,
      label = 'SMOOTH',
      routes = {},
      get_format = function(s, v) return string.format('%.1f', v) end,
      norm_to_real = function(n) return n end,
      real_to_norm = function(r) return r end
    },
    {
      id = 'lfo_delay', type = 'AuraKnob',
      x = 400, y = 50, w = 60, h = 60, radius = 18, align = 1,
      param_key = 'unmapped', default_val = 0.000000, color_token = 'Neutral', is_bipolar = false,
      label = 'DELAY',
      routes = {},
      get_format = function(s, v) return string.format('%.1f', v) end,
      norm_to_real = function(n) return n end,
      real_to_norm = function(r) return r end
    },
    {
      id = 'lfo_rise', type = 'AuraKnob',
      x = 490, y = 50, w = 60, h = 60, radius = 18, align = 1,
      param_key = 'unmapped', default_val = 0.000000, color_token = 'Neutral', is_bipolar = false,
      label = 'RISE',
      routes = {},
      get_format = function(s, v) return string.format('%.1f', v) end,
      norm_to_real = function(n) return n end,
      real_to_norm = function(r) return r end
    },
    {
      id = 'lfo_sync', type = 'TogglePill',
      x = 40, y = 140, w = 50, h = 24, radius = 16, align = 1,
      param_key = 'unmapped', default_val = 1.000000, color_token = 'Primary', is_bipolar = false,
      label = 'SYNC',
      routes = {},
      get_format = function(s, v) return string.format('%.1f', v) end,
      norm_to_real = function(n) return n end,
      real_to_norm = function(r) return r end
    },
    {
      id = 'lfo_flip', type = 'TogglePill',
      x = 100, y = 140, w = 50, h = 24, radius = 16, align = 1,
      param_key = 'unmapped', default_val = 0.000000, color_token = 'Accent', is_bipolar = false,
      label = 'FLIP',
      routes = {},
      get_format = function(s, v) return string.format('%.1f', v) end,
      norm_to_real = function(n) return n end,
      real_to_norm = function(r) return r end
    },
  }
}
