-- AUTO-GENERATED BY OMM VISUAL COMPILER
-- MODULE: GAIN Stage | THEME: Default
-- Protocol Zero: Macro Multiplexing Routes

return {
  grid_cols = 12,
  grid_rows = 6,
  seed_hex = 0x00FF88,
  module_type = "GAIN",
  components = {
    {
      id = 'gain_vol', type = 'AuraKnob',
      x = 30, y = 30, w = 60, h = 60, radius = 28, align = 1,
      color_token = 'Primary', label = 'VOLUME',
      default_val = 0.833,
      routes = {},
      get_format = function(s, v)
        local db = -60.0 + (v * 72.0)
        if db <= -59.9 then return '-INF' end
        return string.format('%+.1f dB', db)
      end,
      norm_to_real = function(n) return n end,
      real_to_norm = function(r) return r end
    },
    {
      id = 'gain_pan', type = 'AuraKnob',
      x = 110, y = 30, w = 60, h = 60, radius = 20, align = 1,
      color_token = 'Neutral', label = 'PAN',
      default_val = 0.5, is_bipolar = true,
      routes = {},
      get_format = function(s, v)
        if math.abs(v - 0.5) < 0.01 then return 'C' end
        if v < 0.5 then return string.format('%.0fL', (0.5 - v) * 200) end
        return string.format('%.0fR', (v - 0.5) * 200)
      end,
      norm_to_real = function(n) return n end,
      real_to_norm = function(r) return r end
    },
  }
}
