-- AUTO-GENERATED BY OMM VISUAL COMPILER
-- MODULE: LFO Core | THEME: Default
-- Protocol Zero: Macro Multiplexing Routes

return {
  grid_cols = 12,
  grid_rows = 6,
  seed_hex = 0x00E5FF,
  module_type = "LFO",
  components = {
    {
      id = 'lfo_rate', type = 'AuraKnob',
      x = 40, y = 50, w = 60, h = 60, radius = 26, align = 1,
      color_token = 'Primary', label = 'RATE',
      default_val = 1.0,
      routes = {},
      get_format = function(s, v) return string.format('%.2f Hz', v) end,
      norm_to_real = function(n) return 0.01 + (n * 39.99) end,
      real_to_norm = function(r) return math.max(0, math.min(1, (r - 0.01) / 39.99)) end
    },
    {
      id = 'lfo_depth', type = 'AuraKnob',
      x = 130, y = 50, w = 60, h = 60, radius = 26, align = 1,
      color_token = 'Accent', label = 'DEPTH',
      default_val = 1.0,
      routes = {},
      get_format = function(s, v) return string.format('%.0f%%', v * 100) end,
      norm_to_real = function(n) return n end,
      real_to_norm = function(r) return r end
    },
    {
      id = 'lfo_phase', type = 'AuraKnob',
      x = 220, y = 50, w = 60, h = 60, radius = 20, align = 1,
      color_token = 'Neutral', label = 'PHASE',
      default_val = 0.0,
      routes = {},
      get_format = function(s, v) return string.format('%.0f°', v * 360) end,
      norm_to_real = function(n) return n end,
      real_to_norm = function(r) return r end
    },
    {
      id = 'lfo_smooth', type = 'AuraKnob',
      x = 310, y = 50, w = 60, h = 60, radius = 18, align = 1,
      color_token = 'Neutral', label = 'SMOOTH',
      default_val = 0.0,
      routes = {},
      get_format = function(s, v) return string.format('%.0f%%', v * 100) end,
      norm_to_real = function(n) return n end,
      real_to_norm = function(r) return r end
    },
    {
      id = 'lfo_delay', type = 'AuraKnob',
      x = 400, y = 50, w = 60, h = 60, radius = 18, align = 1,
      color_token = 'Neutral', label = 'DELAY',
      default_val = 0.0,
      routes = {},
      get_format = function(s, v) return string.format('%.0f%%', v * 100) end,
      norm_to_real = function(n) return n end,
      real_to_norm = function(r) return r end
    },
    {
      id = 'lfo_rise', type = 'AuraKnob',
      x = 490, y = 50, w = 60, h = 60, radius = 18, align = 1,
      color_token = 'Neutral', label = 'RISE',
      default_val = 0.0,
      routes = {},
      get_format = function(s, v) return string.format('%.0f%%', v * 100) end,
      norm_to_real = function(n) return n end,
      real_to_norm = function(r) return r end
    },
    {
      id = 'lfo_sync', type = 'TogglePill',
      x = 40, y = 140, w = 50, h = 24, align = 1,
      color_token = 'Primary', label = 'SYNC',
      default_val = 1.0,
      routes = {},
      get_format = function(s, v) return v > 0.5 and 'ON' or 'OFF' end,
      norm_to_real = function(n) return n > 0.5 and true or false end,
      real_to_norm = function(r) return r and 1.0 or 0.0 end
    },
    {
      id = 'lfo_flip', type = 'TogglePill',
      x = 100, y = 140, w = 50, h = 24, align = 1,
      color_token = 'Accent', label = 'FLIP',
      default_val = 0.0,
      routes = {},
      get_format = function(s, v) return v > 0.5 and 'ON' or 'OFF' end,
      norm_to_real = function(n) return n > 0.5 and true or false end,
      real_to_norm = function(r) return r and 1.0 or 0.0 end
    },
  }
}
