-- AUTO-GENERATED BY OMM VISUAL COMPILER
-- ALGO: 3 | THEME: Default

return {
  grid_cols = 12,
  grid_rows = 6,
  seed_hex = 10878975,
  components = {
    {
      id = 'algo_drop', type = 'Dropdown',
      x = 20, y = 10, w = 150, h = 24, radius = 16, align = 1,
      param_key = 'algo', default_val = 3.000000, color_token = 'Accent_A', is_bipolar = false,
      label = 'COMP TYPE',
      routes = {
        { type = "INTERNAL", target = "algo", depth = 1.0000, label = "algo" },
      },
      get_format = function(s, v) return string.format('%.1f', v) end,
      norm_to_real = function(n) return n end,
      real_to_norm = function(r) return r end
    },
    {
      id = 'vfd_scr', type = 'VFDScreen',
      x = 180, y = 10, w = 80, h = 24, radius = 16, align = 1,
      param_key = 'unmapped', default_val = 0.000000, color_token = 'Teal', is_bipolar = false,
      label = 'GR',
      routes = {},
      get_format = function(s, v) return string.format('%.1f', v) end,
      norm_to_real = function(n) return n end,
      real_to_norm = function(r) return r end
    },
    {
      id = 'th', type = 'InlineDrag',
      x = 20, y = 50, w = 60, h = 20, radius = 16, align = 1,
      param_key = 'thresh', default_val = -18.000000, color_token = 'Teal', is_bipolar = false,
      label = 'TH',
      routes = {
        { type = "INTERNAL", target = "thresh", depth = 1.0000, label = "thresh" },
      },
      get_format = function(s, v) return string.format('%.1f', v) end,
      norm_to_real = function(n) return n end,
      real_to_norm = function(r) return r end
    },
    {
      id = 'rt_comp', type = 'InlineDrag',
      x = 90, y = 50, w = 60, h = 20, radius = 16, align = 1,
      param_key = 'ratio', default_val = 4.000000, color_token = 'Teal', is_bipolar = false,
      label = 'RATIO',
      routes = {
        { type = "INTERNAL", target = "ratio", depth = 1.0000, label = "ratio" },
      },
      get_format = function(s, v) return string.format('%.1f', v) end,
      norm_to_real = function(n) return n end,
      real_to_norm = function(r) return r end
    },
    {
      id = 'tc_radio', type = 'RadioStrip',
      x = 30, y = 100, w = 60, h = 20, radius = 16, align = 1,
      param_key = 'attack', default_val = 0.000000, color_token = 'Tangerine', is_bipolar = false,
      routes = {
        { type = "INTERNAL", target = "attack", depth = 1.0000, label = "attack" },
      },
      get_format = function(s, v) return string.format('%.1f', v) end,
      norm_to_real = function(n) return n end,
      real_to_norm = function(r) return r end
    },
    {
      id = 'kn_rel', type = 'AuraKnob',
      x = 240, y = 100, w = 60, h = 20, radius = 20, align = 1,
      param_key = 'release', default_val = 150.000000, color_token = 'Teal', is_bipolar = false,
      label = 'RELEASE',
      routes = {
        { type = "INTERNAL", target = "release", depth = 1.0000, label = "release" },
      },
      get_format = function(s, v) return string.format('%.1f', v) end,
      norm_to_real = function(n) return n end,
      real_to_norm = function(r) return r end
    },
  }
}
