-- AUTO-GENERATED BY OMM VISUAL COMPILER
-- ALGO: 0 | THEME: Default

return {
  grid_cols = 13,
  grid_rows = 6,
  seed_hex = 10878975,
  active_palette = {
    { id=1, hex=15073279, token='Primary', gen_index=0, hue_drift=0.000000 },
    { id=2, hex=4285216255, token='Accent', gen_index=0, hue_drift=0.000000 },
    { id=3, hex=4126537727, token='Text', gen_index=0, hue_drift=0.000000 },
    { id=4, hex=2391708671, token='Neutral', gen_index=0, hue_drift=0.000000 },
    { id=5, hex=471604991, token='Base', gen_index=0, hue_drift=0.000000 },
  },
  components = {
    {
      id = 'err_txt', type = 'TogglePill',
      x = 210, y = 32, w = 32, h = 18, radius = 16, align = 1,
      param_key = 'unmapped', default_val = 1.000000, color_token = 'Primary', is_bipolar = false,
      label = 'SCHEMA MISSING',
      routes = {},
      get_format = function(s, v) return string.format('%.1f', v) end,
      norm_to_real = function(n) return n end,
      real_to_norm = function(r) return r end
    },
    {
      id = 'ReaComp_AuraKnob_6268', type = 'AuraKnob',
      x = 103, y = 72, w = 32, h = 32, radius = 26, align = 1,
      param_key = 'unmapped', default_val = 0.000000, color_token = 'Accent_B', is_bipolar = false,
      label = 'AURAKNOB',
      routes = {
        { type = "INTERNAL", target = "thresh", depth = 1.0000, label = "Threshold" },
      },
      get_format = function(s, v) return string.format('%.1f', v) end,
      norm_to_real = function(n) return n end,
      real_to_norm = function(r) return r end
    },
    {
      id = 'ReaComp_Fader_5480', type = 'Fader',
      x = 17, y = 70, w = 30, h = 120, radius = 16, align = 1,
      param_key = 'unmapped', default_val = 0.000000, color_token = 'Teal', is_bipolar = false,
      label = 'FADER',
      routes = {},
      get_format = function(s, v) return string.format('%.1f', v) end,
      norm_to_real = function(n) return n end,
      real_to_norm = function(r) return r end
    },
    {
      id = 'ReaComp_ToggleLever_1010', type = 'ToggleLever',
      x = 216, y = 78, w = 20, h = 41, radius = 16, align = 1,
      param_key = 'unmapped', default_val = 0.000000, color_token = 'Teal', is_bipolar = false,
      label = 'TOGGLELEVER',
      routes = {},
      get_format = function(s, v) return string.format('%.1f', v) end,
      norm_to_real = function(n) return n end,
      real_to_norm = function(r) return r end
    },
    {
      id = 'ReaComp_Dropdown_5423', type = 'Dropdown',
      x = 288, y = 27, w = 140, h = 28, radius = 16, align = 1,
      param_key = 'unmapped', default_val = 0.000000, color_token = 'Teal', is_bipolar = false,
      label = 'DROPDOWN',
      routes = {},
      get_format = function(s, v) return string.format('%.1f', v) end,
      norm_to_real = function(n) return n end,
      real_to_norm = function(r) return r end
    },
    {
      id = 'ReaComp_RadioStrip_3453', type = 'RadioStrip',
      x = 314, y = 165, w = 192, h = 25, radius = 16, align = 1,
      param_key = 'unmapped', default_val = 0.000000, color_token = 'Teal', is_bipolar = false,
      label = 'RADIOSTRIP',
      routes = {},
      get_format = function(s, v) return string.format('%.1f', v) end,
      norm_to_real = function(n) return n end,
      real_to_norm = function(r) return r end
    },
  }
}
